import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

def plot_velocity_only(csv_filepath: str) -> None:
    try:
        df = pd.read_csv(csv_filepath)
    except FileNotFoundError:
        print(f"File not found: {csv_filepath}")
        return

    # Extract the required arrays
    t = df['t (s)']
    rpm = df['RPM']

    # Initialize a single plot figure
    plt.figure(figsize=(10, 6))
    manager = plt.gcf().canvas.manager
    if manager is not None:
        manager.set_window_title('MIXR-1 Velocity Viewer')

    # Plot Velocity vs. Time
    plt.plot(t, rpm, color='#58a6ff', linewidth=2)
    plt.title('System Velocity vs. Time', fontweight='bold', fontsize=14)
    plt.xlabel('Time (s)', fontweight='bold')
    plt.ylabel('Velocity (RPM)', fontweight='bold')
    
    # Set x-axis ticks to multiples of 5 (or change to 1 for 1, 2, 3...)
    ax = plt.gca()
    ax.xaxis.set_major_locator(ticker.MultipleLocator(5))
    ax.tick_params(axis='x', rotation=45) # Rotate for better visibility if clustered
    
    plt.grid(True, linestyle=':', alpha=0.6)

    # Automatically adjust layout and render
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    # Replace with the exact filename generated by your PyQt6 dashboard
    target_csv = "mixr1_log_20260623_161326.csv" 
    plot_velocity_only(target_csv)